accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.profile, name='profile'),
    url(r'^edit/$', views.edit_profile, name='edit_profile'),
]

cfp/urls.py
from django.conf.urls import url

from . import views

app_name = 'cfp'

urlpatterns = [
    url(r'^proposals/new/$', views.new_proposal, name='new_proposal'),
    url(r'^proposals/(?P<proposal_id>\w+)/$', views.proposal, name='proposal'),
    url(r'^proposals/(?P<proposal_id>\w+)/edit/$', views.proposal_edit, name='proposal_edit'),
    url(r'^proposals/(?P<proposal_id>\w+)/delete/$', views.proposal_delete, name='proposal_delete'),
    url(r'^voting/$', views.voting_index, name='voting_index'),
    url(r'^voting/reviewed/$', views.voting_reviewed_proposals, name='voting_reviewed_proposals'),
    url(r'^voting/unreviewed/$', views.voting_unreviewed_proposals, name='voting_unreviewed_proposals'),
    url(r'^voting/of-interest/$', views.voting_proposals_of_interest, name='voting_proposals_of_interest'),
    url(r'^voting/not-of-interest/$', views.voting_proposals_not_of_interest, name='voting_proposals_not_of_interest'),
    url(r'^voting/proposals/(?P<proposal_id>\w+)/$', views.voting_proposal, name='voting_proposal'),
]

children/urls.py
from django.conf.urls import url

from . import views

app_name = 'children'

urlpatterns = [
    url(r'^orders/new/$', views.new_order, name='new_order'),
    url(r'^orders/(?P<order_id>\w+)/$', views.order, name='order'),
    url(r'^orders/(?P<order_id>\w+)/edit/$', views.order_edit, name='order_edit'),
    url(r'^orders/(?P<order_id>\w+)/payment/$', views.order_payment, name='order_payment'),
]

ironcage/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

import accounts.views
import ironcage.views


if settings.MAINTENANCE_MODE:
    urlpatterns = [
        url('.*', ironcage.views.maintenance_mode)
    ]
else:
    urlpatterns = [
        url(r'^accounts/register/', accounts.views.register, name='register'),
        url(r'^accounts/', include('django.contrib.auth.urls')),
        url(r'^accommodation/', include('accommodation.urls')),
        url(r'^admin/', admin.site.urls),
        url(r'^children/', include('children.urls')),
        url(r'^cfp/', include('cfp.urls')),
        url(r'^dinners/', include('dinners.urls')),
        url(r'^grants/', include('grants.urls')),
        url(r'^profile/', include('accounts.urls')),
        url(r'^reports/', include('reports.urls')),
        url(r'^tickets/', include('tickets.urls')),
        url(r'^ukpa/', include('ukpa.urls')),
        url(r'^$', ironcage.views.index, name='index'),
        url(r'^500/$', ironcage.views.error, name='error'),
        url(r'^log/$', ironcage.views.log, name='log'),
        url(r'^avatar/', include('avatar.urls')),
        url(r'^payments/', include('payments.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

tickets/urls.py
from django.conf.urls import url

from . import views

app_name = 'tickets'

urlpatterns = [
    url(r'^orders/new/$', views.new_order, name='new_order'),
    url(r'^orders/confirm/$', views.order_confirm, name='order_confirm'),
    url(r'^orders/edit/$', views.order_edit, name='order_edit'),
    url(r'^tickets/(?P<ticket_id>\w+)/$', views.ticket, name='ticket'),
    url(r'^tickets/(?P<ticket_id>\w+)/edit/$', views.ticket_edit, name='ticket_edit'),
    url(r'^invitations/(?P<token>\w+)/$', views.ticket_invitation, name='ticket_invitation'),
]

tickets/forms.py
from django import forms
from django.core.exceptions import ValidationError

from ironcage.widgets import ButtonsCheckbox, ButtonsRadio, EmailInput

from tickets.models import Ticket


WHO_CHOICES = [
    ('self', 'Myself'),
    ('others', 'Other people'),
    ('self and others', 'Myself and other people'),
]


DAY_CHOICES = [
    ('sat', 'Saturday'),
    ('sun', 'Sunday'),
    ('mon', 'Monday'),
    ('tue', 'Tuesday'),
    ('wed', 'Wednesday'),
]

RATE_CHOICES = [
    (Ticket.INDIVIDUAL, 'Individual'),
    (Ticket.CORPORATE, 'Corporate'),
    (Ticket.EDUCATION, 'Education'),
]


class TicketForm(forms.Form):
    who = forms.ChoiceField(
        choices=WHO_CHOICES,
        widget=ButtonsRadio
    )
    rate = forms.ChoiceField(
        choices=RATE_CHOICES,
        widget=ButtonsRadio
    )


class TicketForSelfForm(forms.Form):
    days = forms.MultipleChoiceField(
        choices=DAY_CHOICES,
        widget=ButtonsCheckbox
    )


class TicketForOtherForm(forms.Form):
    email_addr = forms.EmailField(
        widget=EmailInput(attrs={'class': 'form-control'}),
    )
    days = forms.MultipleChoiceField(
        choices=DAY_CHOICES,
        widget=ButtonsCheckbox
    )


class BaseTicketForOthersFormset(forms.BaseFormSet):
    def clean(self):
        self.email_addrs_and_days = []
        for form in self.forms:
            if form.errors:
                continue

            if not form.cleaned_data:
                # This was an empty form, so we ignore it
                continue

            email_addr = form.cleaned_data['email_addr']
            days = form.cleaned_data['days']
            self.email_addrs_and_days.append((email_addr, days))

        if not self.email_addrs_and_days:
            raise ValidationError('No valid forms')


TicketForOthersFormSet = forms.formset_factory(
    TicketForOtherForm,
    formset=BaseTicketForOthersFormset,
    min_num=1,
    extra=1,
    can_delete=True
)


class CompanyDetailsForm(forms.Form):
    company_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    company_addr = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'})
    )

tickets/views.py
from decimal import Decimal

from datetime import datetime, timezone

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.utils.safestring import mark_safe

from payments import actions as payment_actions
from . import actions
from .forms import CompanyDetailsForm, TicketForm, TicketForSelfForm, TicketForOthersFormSet
from .models import Ticket, TicketInvitation
from .prices import PRICES_INCL_VAT, cost_incl_vat
from .constants import DAYS


def new_order(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect(settings.LOGIN_URL)

        form = TicketForm(request.POST)
        self_form = TicketForSelfForm(request.POST)
        others_formset = TicketForOthersFormSet(request.POST)
        company_details_form = CompanyDetailsForm(request.POST)

        if form.is_valid():
            who = form.cleaned_data['who']
            rate = form.cleaned_data['rate']

            if who == 'self':
                valid = self_form.is_valid()
                if valid:
                    days_for_self = self_form.cleaned_data['days']
                    email_addrs_and_days_for_others = None
            elif who == 'others':
                valid = others_formset.is_valid()
                if valid:
                    days_for_self = None
                    email_addrs_and_days_for_others = others_formset.email_addrs_and_days
            elif who == 'self and others':
                valid = self_form.is_valid() and others_formset.is_valid()
                if valid:
                    days_for_self = self_form.cleaned_data['days']
                    email_addrs_and_days_for_others = others_formset.email_addrs_and_days
            else:
                assert False

            if valid:
                if rate == Ticket.CORPORATE:
                    valid = company_details_form.is_valid()
                    if valid:
                        company_details = {
                            'name': company_details_form.cleaned_data['company_name'],
                            'addr': company_details_form.cleaned_data['company_addr'],
                        }
                else:
                    company_details = None

            if valid:

                request.session['ticket_details'] = {
                    'rate': rate,
                    'days_for_self': days_for_self,
                    'email_addrs_and_days_for_others': email_addrs_and_days_for_others,
                    'company_details': company_details,
                    'form': form.data,
                    'self_form': self_form.data,
                    'others_formset': others_formset.data,
                    'company_details_form': company_details_form.data,
                }

                return redirect('tickets:order_confirm')

    else:
        if datetime.now(timezone.utc) > settings.TICKET_SALES_CLOSE_AT:
            if request.GET.get('deadline-bypass-token', '') != settings.TICKET_DEADLINE_BYPASS_TOKEN:
                messages.warning(request, "We're sorry, ticket sales have closed")
                return redirect('index')

        form = TicketForm()
        self_form = TicketForSelfForm()
        others_formset = TicketForOthersFormSet()
        company_details_form = CompanyDetailsForm()

    context = {
        'form': form,
        'self_form': self_form,
        'others_formset': others_formset,
        'company_details_form': company_details_form,
        'user_can_buy_for_self': request.user.is_authenticated and not request.user.get_ticket(),
        'rates_table_data': _rates_table_data(),
        'rates_data': _rates_data(),
        'js_paths': ['tickets/order_form.js'],
    }

    return render(request, 'tickets/new_order.html', context)


@login_required
def order_confirm(request):

    details = request.session['ticket_details']

    if request.method == 'POST':

        print(details)

        invoice = actions.create_invoice_with_tickets(
            request.user,
            details['rate'],
            details['days_for_self'],
            details['email_addrs_and_days_for_others'],
            details['company_details'],
        )

        return redirect(invoice)

    else:

        RATES = {
            'INDI': 'Individual',
            'CORP': 'Corporate',
            'EDUC': 'Education',
        }

        order_total = Decimal()

        number_of_tickets = 0
        if details['email_addrs_and_days_for_others']:
            number_of_tickets += len(details['email_addrs_and_days_for_others'])
        if details['days_for_self']:
            number_of_tickets += 1

        rate = RATES[details['rate']]

        details_for_self = {}

        if details['days_for_self']:
            details_for_self['days'] = [DAYS[day] for day in details['days_for_self']]
            details_for_self['amount'] = cost_incl_vat(details['rate'], len(details['days_for_self']))
            order_total += details_for_self['amount']

        details_for_others = []
        if details['email_addrs_and_days_for_others']:
            for email, days in details['email_addrs_and_days_for_others']:
                details_for_others.append((
                    email,
                    [DAYS[day] for day in days],
                    cost_incl_vat(details['rate'], len(days))
                ))
                order_total += cost_incl_vat(details['rate'], len(days))

        context = {
            'rate': rate,
            'number_of_tickets': number_of_tickets,
            'details_for_self': details_for_self,
            'details_for_others': details_for_others,
            'order_total': order_total,
            'company_details': details['company_details'],
        }

        return render(request, 'tickets/order_confirm.html', context)


@login_required
def order_edit(request):

    if request.method == 'POST':
        form = TicketForm(request.POST)
        self_form = TicketForSelfForm(request.POST)
        others_formset = TicketForOthersFormSet(request.POST)
        company_details_form = CompanyDetailsForm(request.POST)

        if form.is_valid():
            who = form.cleaned_data['who']
            rate = form.cleaned_data['rate']

            if who == 'self':
                valid = self_form.is_valid()
                if valid:
                    days_for_self = self_form.cleaned_data['days']
                    email_addrs_and_days_for_others = None
            elif who == 'others':
                valid = others_formset.is_valid()
                if valid:
                    days_for_self = None
                    email_addrs_and_days_for_others = others_formset.email_addrs_and_days
            elif who == 'self and others':
                valid = self_form.is_valid() and others_formset.is_valid()
                if valid:
                    days_for_self = self_form.cleaned_data['days']
                    email_addrs_and_days_for_others = others_formset.email_addrs_and_days
            else:
                assert False

            if valid:
                if rate == 'corporate':
                    valid = company_details_form.is_valid()
                    if valid:
                        company_details = {
                            'name': company_details_form.cleaned_data['company_name'],
                            'addr': company_details_form.cleaned_data['company_addr'],
                        }
                else:
                    company_details = None

            if valid:
                request.session['ticket_details'] = {
                    'rate': rate,
                    'days_for_self': days_for_self,
                    'email_addrs_and_days_for_others': email_addrs_and_days_for_others,
                    'company_details': company_details,
                    'form': form.data,
                    'self_form': self_form.data,
                    'others_formset': others_formset.data,
                    'company_details_form': company_details_form.data,
                }

                return redirect('tickets:order_confirm')

    else:
        form = TicketForm(request.session['ticket_details']['form'])
        self_form = TicketForSelfForm(request.session['ticket_details']['self_form'])
        others_formset = TicketForOthersFormSet(request.session['ticket_details']['others_formset'])
        company_details_form = CompanyDetailsForm(request.session['ticket_details']['company_details_form'])

    context = {
        'form': form,
        'self_form': self_form,
        'others_formset': others_formset,
        'company_details_form': company_details_form,
        'user_can_buy_for_self': not request.user.get_ticket(),
        'rates_table_data': _rates_table_data(),
        'rates_data': _rates_data(),
        'js_paths': ['tickets/order_form.js'],
    }

    return render(request, 'tickets/order_edit.html', context)


@login_required
def ticket(request, ticket_id):
    ticket = Ticket.objects.get_by_ticket_id_or_404(ticket_id)

    if request.user != ticket.owner:
        messages.warning(request, 'Only the owner of a ticket can view the ticket')
        return redirect('index')

    if ticket.is_free_ticket() and ticket.is_incomplete():
        return redirect('tickets:ticket_edit', ticket.ticket_id)

    if not request.user.profile_complete():
        messages.warning(request, mark_safe('Your profile is incomplete. <a href="{}">Update your profile</a>'.format(reverse('accounts:profile'))))

    context = {
        'ticket': ticket,
    }
    return render(request, 'tickets/ticket.html', context)


@login_required
def ticket_edit(request, ticket_id):
    ticket = Ticket.objects.get_by_ticket_id_or_404(ticket_id)

    if request.user != ticket.owner:

tickets/templates/tickets/_order_form.html
<form method="post" id="order-form">
  {% csrf_token %}
  <div class="panel panel-default">
    <div class="panel-heading">About your order</div>
    <div class="panel-body">
      {% if user_can_buy_for_self %}
      <div class="row">
        <div class="col-md-4">
          <label>Who are you buying tickets for?</label>
        </div>
        <div class="col-md-8">
          <div class="btn-group" data-toggle="buttons">
            {{ form.who }}
          </div>
        </div>
      </div>
      {% else %}
      <input type="hidden" name="who" value="others">
      {% endif %}

      <div class="row">
        <div class="col-md-4">
          <label>What rate of tickets are you buying?</label>
        </div>
        <div class="col-md-8">
          <div class="btn-group" data-toggle="buttons">
            {{ form.rate }}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default" id="form-panel-self">
    <div class="panel-heading">Your own ticket</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <label>Which days are you coming?</label>
        </div>
        <div class="col-md-8">
          <div class="btn-group{% if self_form.days.errors %} error{% endif %}" data-toggle="buttons">
            {{ self_form.days }}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default" id="form-panel-others">
    <div class="panel-heading">Other people's tickets</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-12">
          <p>For each person you're buying a ticket for, enter their email address and the days which they are coming.</p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>Email address</label>
        </div>
        <div class="col-md-8">
          <label>Days</label>
        </div>
      </div>

      <div id="formset" data-formset-prefix="{{ others_formset.prefix }}">
        {{ others_formset.management_form }}

        <div data-formset-body>
          {% for form in others_formset %}
          {% include 'tickets/_others_form.html' with form=form %}
          {% endfor %}
        </div>

        <script type="form-template" data-formset-empty-form>
          {% include 'tickets/_others_form.html' with form=others_formset.empty_form %}
        </script>

        <input type="button" value="Add another" data-formset-add class="btn btn-default">
      </div>
    </div>
  </div>

  <div class="panel panel-default" id="form-panel-company-details">
    <div class="panel-heading">Company details</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <label>Company name</label>
        </div>
        <div class="col-md-6">
          {{ company_details_form.company_name }}
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <label>Company address</label>
        </div>
        <div class="col-md-6">
          {{ company_details_form.company_addr }}
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default" id="form-panel-submit">
    <div class="panel-heading">Summary</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <table class="table">
            <tr>
              <th>Rate</th>
              <td><span id="rate"></span></td>
            </tr>
            <tr>
              <th>Number of tickets</th>
              <td><span id="num-tickets">0</span></td>
            </tr>
            <tr>
              <th>Total cost (incl. VAT)</th>
              <td>&pound;<span id="total-cost">0</span></td>
            </tr>
          </table>
          <input type="submit" value="Place my order" class="btn btn-primary" />
        </div>
      </div>
    </div>
  </div>
</form>

tickets/templates/tickets/_others_form.html
<div data-formset-form>
  <div class="row">
    <div class="col-xs-4">
      {{ form.email_addr }}
    </div>
    <div class="col-xs-6">
      <div class="btn-group{% if form.days.errors %} error{% endif %}" data-toggle="buttons">
        {{ form.days }}
      </div>
    </div>
    <div class="col-xs-1">
      <div class="hidden">{{ form.DELETE }}</div>
      <button type="button" data-formset-delete-button class="btn btn-default">&times;</button>
    </div>
  </div>
</div>

tickets/templates/tickets/_ticket_details.html
<table class="table">
  <tr>
    <th>Ticket holder</th>
    <td>{{ ticket.owner.name }}</td>
  </tr>
  <tr>
    <th>Days</th>
    <td>{{ ticket.details.days }}</td>
  </tr>
  {% if not ticket.is_free_ticket %}
  <tr>
    <th>Cost (incl. VAT)</th>
    <td>{{ ticket.details.cost_incl_vat }}</td>
  </tr>
  {% endif %}
  <tr>
    <th>Accessibility</th>
    <td>
      {% if user.accessibility_reqs_yn == None %}
      unknown
      {% elif user.accessibility_reqs_yn %}
      {{ user.accessibility_reqs }}
      {% else %}
      none
      {% endif %}
    </td>
  </tr>
  <tr>
    <th>Childcare</th>
    <td>
      {% if user.childcare_reqs_yn == None %}
      unknown
      {% elif user.childcare_reqs_yn %}
      {{ user.childcare_reqs }}
      {% else %}
      none
      {% endif %}
    </td>
  </tr>
  <tr>
    <th>Dietary</th>
    <td>
      {% if user.dietary_reqs_yn == None %}
      unknown
      {% elif user.dietary_reqs_yn %}
      {{ user.dietary_reqs }}
      {% else %}
      none
      {% endif %}
    </td>
  </tr>
</table>

tickets/templates/tickets/_ticket_info.html
<p>Tickets are available for between one and five days of the conference.</p>
<p>If you are paying for your own ticket, you should pay at the Individual rate.  If your company is paying for your ticket, you should pay at the Corporate rate.</p>
<p>Teachers and those in full time education should pay at the Education rate.</p>
<p>All prices include VAT at 20%.</p>
<!-- <p>Children's day tickets are available separately <a href={% url 'children:new_order' %}>here</a>.</p> -->

tickets/templates/tickets/_ticket_price_table.html
<table class="table table-condensed table-striped">
  {% for row in rates_table_data %}
  <tr>
    {% for item in row %}
    <td class="text-center">{{ item }}</td>
    {% endfor %}
  </tr>
  {% endfor %}
</table>

tickets/templates/tickets/new_order.html
{% extends 'ironcage/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6">
    {% if not request.user.is_authenticated %}
    <p>Please <a href="{% url 'register' %}?next={{ request.path }}">sign up</a> or <a href="{% url 'login' %}?next={{ request.path }}">sign in</a> to buy a ticket.</p>
    <p>If you bought a ticket for last years conference, you can sign in with the same account.</p>
    {% endif %}

    {% include './_ticket_info.html' %}
  </div>

  <div class="col-md-6">
    {% include './_ticket_price_table.html' %}
  </div>
</div>

<div class="row">
  {% if request.user.is_authenticated %}
  {% include 'tickets/_order_form.html' %}
  {% endif %}
</div>
{% endblock %}

{% block json_data %}
var rates = {{ rates_data|safe }};
{% endblock %}

tickets/templates/tickets/order_confirm.html
{% extends 'ironcage/base.html' %}

{% block content %}
<h1>Confirm your order</h1>

<div class="row">
  <div class="col-md-9">
    <p>You have ordered {{ number_of_tickets }} ticket{{ number_of_tickets|pluralize }} at the {{ rate }} rate.</p>

    {% if company_details %}
    <p>Invoiced to {{ company_details.name }}</p>
    <p>{{ company_details.addr }}</p>
    {% endif %}

    {% if details_for_self %}
        <h2>Your ticket</h2>
        <p>You have ordered a ticket for yourself for {{ details_for_self.days|length }} day{{ details_for_self.days|pluralize }} ({{ details_for_self.days|join:", " }}) at a cost of &pound;{{ details_for_self.amount|floatformat:2 }} (inc VAT).</p>
    {% endif %}

    {% if details_for_others %}
        <h2>Tickets for others</h2>
        {% for email, days, price in details_for_others %}
            <p>You have ordered a ticket for {{ email }} for {{ days|length }} day{{ days|pluralize }} ({{ days|join:", " }}) at a cost of &pound;{{ price|floatformat:2 }} (inc VAT).</p>
        {% endfor %}
    {% endif %}

    <h2>Order Total</h2>
    <p>The order total comes to &pound;{{ order_total|floatformat:2 }} (inc VAT).</p>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Place order" class="btn btn-primary" />
        <a href="{% url 'tickets:order_edit' %}" class="btn btn-primary">Make changes</a>
    </form>
  </div>
</div>

{% endblock %}

tickets/templates/tickets/order_edit.html
{% extends 'ironcage/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6">
    {% include './_ticket_info.html' %}
  </div>

  <div class="col-md-6">
    {% include './_ticket_price_table.html' %}
  </div>
</div>

<div class="row">
  {% include 'tickets/_order_form.html' %}
</div>
{% endblock %}

{% block json_data %}
var rates = {{ rates_data|safe }};
{% endblock %}

tickets/templates/tickets/ticket.html
{% extends 'ironcage/base.html' %}

{% block content %}
<h1>Details of your ticket ({{ ticket.ticket_id }})</h1>

<div class="row">
  <div class="col-md-6">
    {% include './_ticket_details.html' %}

    <a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary">Update your profile</a>
    {% if ticket.is_free_ticket %}
    <a href="{% url 'tickets:ticket_edit' ticket_id=ticket.ticket_id %}" class="btn btn-primary">Update your ticket</a>
    {% endif %}
  </div>
</div>

{% endblock %}

tickets/templates/tickets/ticket_edit.html
{% extends 'ironcage/base.html' %}

{% block content %}
<h1>Update your ticket ({{ ticket.ticket_id }})</h1>

<form method="post">
  {% csrf_token %}
  <div class="panel panel-default">
    <div class="panel-heading">Your ticket</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <label>Which days are you coming?</label>
        </div>
        <div class="col-md-8">
          <div class="btn-group{% if form.days.errors %} error{% endif %}" data-toggle="buttons">
            {{ form.days }}
          </div>
        </div>
        <div class="col-md-4">
          <input type="submit" value="Update my ticket" class="btn btn-primary" />
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}