accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.profile, name='profile'),
    url(r'^edit/$', views.edit_profile, name='edit_profile'),
]

cfp/urls.py
from django.conf.urls import url

from . import views

app_name = 'cfp'

urlpatterns = [
    url(r'^proposals/new/$', views.new_proposal, name='new_proposal'),
    url(r'^proposals/(?P<proposal_id>\w+)/$', views.proposal, name='proposal'),
    url(r'^proposals/(?P<proposal_id>\w+)/edit/$', views.proposal_edit, name='proposal_edit'),
    url(r'^proposals/(?P<proposal_id>\w+)/delete/$', views.proposal_delete, name='proposal_delete'),
    url(r'^voting/$', views.voting_index, name='voting_index'),
    url(r'^voting/reviewed/$', views.voting_reviewed_proposals, name='voting_reviewed_proposals'),
    url(r'^voting/unreviewed/$', views.voting_unreviewed_proposals, name='voting_unreviewed_proposals'),
    url(r'^voting/of-interest/$', views.voting_proposals_of_interest, name='voting_proposals_of_interest'),
    url(r'^voting/not-of-interest/$', views.voting_proposals_not_of_interest, name='voting_proposals_not_of_interest'),
    url(r'^voting/proposals/(?P<proposal_id>\w+)/$', views.voting_proposal, name='voting_proposal'),
]

ironcage/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

import accounts.views
import ironcage.views


if settings.MAINTENANCE_MODE:
    urlpatterns = [
        url('.*', ironcage.views.maintenance_mode)
    ]
else:
    urlpatterns = [
        url(r'^accounts/register/', accounts.views.register, name='register'),
        url(r'^accounts/', include('django.contrib.auth.urls')),
        url(r'^accommodation/', include('accommodation.urls')),
        url(r'^admin/', admin.site.urls),
        url(r'^children/', include('children.urls')),
        url(r'^cfp/', include('cfp.urls')),
        url(r'^dinners/', include('dinners.urls')),
        url(r'^grants/', include('grants.urls')),
        url(r'^profile/', include('accounts.urls')),
        url(r'^reports/', include('reports.urls')),
        url(r'^tickets/', include('tickets.urls')),
        url(r'^ukpa/', include('ukpa.urls')),
        url(r'^$', ironcage.views.index, name='index'),
        url(r'^500/$', ironcage.views.error, name='error'),
        url(r'^log/$', ironcage.views.log, name='log'),
        url(r'^avatar/', include('avatar.urls')),
        url(r'^payments/', include('payments.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/models.py
import json
import os

from django.conf import settings
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.shortcuts import get_object_or_404

from accommodation.models import Booking
from grants.models import Application
from ironcage.utils import Scrambler
from tickets.models import Ticket
from ukpa.models import Nomination

from .managers import UserManager


# https://en.wikipedia.org/wiki/Member_states_of_the_United_Nations
with open(os.path.join(settings.BASE_DIR, 'accounts', 'data', 'countries.txt')) as f:
    COUNTRIES = [line.strip() for line in f]

# https://en.wikipedia.org/wiki/List_of_adjectival_and_demonymic_forms_for_countries_and_nations
with open(os.path.join(settings.BASE_DIR, 'accounts', 'data', 'nationalities.txt')) as f:
    NATIONALITIES = [line.strip() for line in f]

# https://www.ons.gov.uk/ons/guide-method/harmonisation/primary-set-of-harmonised-concepts-and-questions/ethnic-group.pdf
with open(os.path.join(settings.BASE_DIR, 'accounts', 'data', 'ethnicities.json')) as f:
    ETHNICITIES = json.load(f)


class Manager(UserManager):
    def get_by_user_id_or_404(self, user_id):
        id = self.model.id_scrambler.backward(user_id)
        return get_object_or_404(self.model, pk=id)


class User(AbstractBaseUser, PermissionsMixin):
    YEAR_OF_BIRTH_CHOICES = [['not shared', 'prefer not to say']] + [[str(year), str(year)] for year in range(1917, 2017)]

    GENDER_CHOICES = [
        ['not shared', 'prefer not to say'],
        ['female', 'female'],
        ['male', 'male'],
        ['other', 'please specify'],
    ]

    COUNTRY_CHOICES = [['not shared', 'prefer not to say']] + [[country, country] for country in COUNTRIES] + [['other', 'not listed here (please specify)']]

    NATIONALITY_CHOICES = [['not shared', 'prefer not to say']] + [[nationality, nationality] for nationality in NATIONALITIES] + [['other', 'not listed here (please specify)']]

    # Sorry
    ETHNICITY_CHOICES = [['not shared', 'prefer not to say']] + [[ethnicity_category, [[ethnicity, ethnicity] for ethnicity in ethnicities]] for ethnicity_category, ethnicities in ETHNICITIES]

    email_addr = models.EmailField(
        'email address',
        unique=True,
        error_messages={
            'unique': 'That email address has already been registered',
        },
    )
    name = models.CharField(max_length=200)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    year_of_birth = models.CharField(max_length=10, null=True, blank=True, choices=YEAR_OF_BIRTH_CHOICES)
    gender = models.CharField(max_length=100, null=True, blank=True, choices=GENDER_CHOICES)
    ethnicity = models.CharField(max_length=100, null=True, blank=True, choices=ETHNICITY_CHOICES)
    ethnicity_free_text = models.CharField(max_length=100, null=True, blank=True)
    nationality = models.CharField(max_length=100, null=True, blank=True, choices=NATIONALITY_CHOICES)
    country_of_residence = models.CharField(max_length=100, null=True, blank=True, choices=COUNTRY_CHOICES)
    dont_ask_demographics = models.BooleanField(default=False)
    accessibility_reqs_yn = models.NullBooleanField()
    accessibility_reqs = models.TextField(null=True, blank=True)
    childcare_reqs_yn = models.NullBooleanField()
    childcare_reqs = models.TextField(null=True, blank=True)
    dietary_reqs_yn = models.NullBooleanField()
    dietary_reqs = models.TextField(null=True, blank=True)
    is_ukpa_member = models.NullBooleanField(null=True, blank=True)
    has_booked_hotel = models.NullBooleanField()
    volunteer_setup = models.NullBooleanField()
    volunteer_session_chair = models.NullBooleanField()
    volunteer_videoer = models.NullBooleanField()
    volunteer_reg_desk = models.NullBooleanField()
    is_contributor = models.BooleanField(default=False)
    coming_to_dojo = models.NullBooleanField()
    coming_to_board_games = models.NullBooleanField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email_addr'
    EMAIL_FIELD = 'email_addr'
    REQUIRED_FIELDS = ['name']

    id_scrambler = Scrambler(8000)

    objects = Manager()

    @property
    def user_id(self):
        if self.id is None:
            return None
        return self.id_scrambler.forward(self.id)

    def get_full_name(self):
        '''This is used by the admin.'''
        return self.name

    def get_short_name(self):
        '''This is used by the admin.'''
        return self.name

    def get_ticket(self):
        try:
            if self.ticket and (self.ticket.rate == Ticket.FREE or self.ticket.invoice.successful_payment):
                return self.ticket
            return None
        except Ticket.DoesNotExist:
            return None

    def get_accommodation_booking(self):
        try:
            return self.booking
        except Booking.DoesNotExist:
            return None

    def get_grant_application(self):
        try:
            return self.grant_application
        except Application.DoesNotExist:
            return None

    def get_nomination(self):
        try:
            return self.nomination
        except Nomination.DoesNotExist:
            return None

    def profile_complete(self):
        if any(v is None for v in [
            self.accessibility_reqs_yn,
            self.childcare_reqs_yn,
            self.dietary_reqs_yn,
        ]):
            return False

        if self.get_ticket() is not None and self.is_ukpa_member is None:
            return False

        if self.dont_ask_demographics:
            return True

        return all(v for v in [
            self.year_of_birth,
            self.gender,
            self.ethnicity,
            self.nationality,
            self.country_of_residence
        ])

    def submitted_single_proposal(self):
        return len(self.proposals.all()) == 1

    def accepted_proposals(self):
        return [p for p in self.proposals.all() if p.is_accepted()]

    def rejected_proposals(self):
        return [p for p in self.proposals.all() if p.is_rejected()]

    def all_proposals_accepted(self):
        return len(self.proposals.all()) > 0 and len(self.proposals.all()) == len(self.accepted_proposals())

    def any_proposals_accepted(self):
        return len(self.accepted_proposals()) > 0

    def some_proposals_accepted(self):
        return self.any_proposals_accepted() and not self.all_proposals_accepted()

    def one_proposal_rejected(self):
        return len(self.rejected_proposals()) == 1

    def one_proposal_accepted(self):
        return len(self.accepted_proposals()) == 1

    def things_volunteered_for(self):
        things = []
        if self.volunteer_setup:
            things.append('Help with setup at 6am on Thursday morning')
        if self.volunteer_session_chair:
            things.append('Chair a session')
        if self.volunteer_videoer:
            things.append('Help with videoing talks')
        if self.volunteer_reg_desk:
            things.append('Staff the registration desk')
        return things

    def get_free_dinner_booking(self):
        if not self.is_contributor:
            return None

        return self.dinner_bookings.filter(stripe_charge_id=None).first()

    def get_contributors_dinner_booking(self):
        return self.dinner_bookings.filter(venue='contributors').first()

    def get_conference_dinner_booking(self):
        return self.dinner_bookings.filter(venue='conference').first()

accounts/forms.py
from contextlib import suppress

from django import forms
from django.contrib.auth import password_validation

from .models import User


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label='Password confirmation',
        widget=forms.PasswordInput,
        strip=False,
        help_text='Enter the same password as before, for verification.',
    )

    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }

    class Meta:
        model = User
        fields = [
            'email_addr',
            'name',
            'password1',
            'password2'
        ]

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'name',
            'email_addr',
            'volunteer_setup',
            'volunteer_session_chair',
            'volunteer_videoer',
            'volunteer_reg_desk',
            'coming_to_dojo',
            'coming_to_board_games',
            'accessibility_reqs_yn',
            'accessibility_reqs',
            'childcare_reqs_yn',
            'childcare_reqs',
            'dietary_reqs_yn',
            'dietary_reqs',
            'is_ukpa_member',
            'dont_ask_demographics',
            'year_of_birth',
            'gender',
            'ethnicity',
            'ethnicity_free_text',
            'nationality',
            'country_of_residence',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # If user has chosen a gender/nationality/country_of_residence that's
        # not in the initial list of choices, we add it to the list here so
        # that they see in in the dropdown when they edit their profile.
        for key in ['gender', 'nationality', 'country_of_residence']:
            widget = self.fields[key].widget
            choices = [choice[0] for choice in widget.choices]
            value = getattr(self.instance, key)
            if value is not None and value not in choices:
                widget.choices.insert(1, [value, value])

        # If the user has not bought a ticket, we do not offer UKPA membership.
        # The option is hidden in the templates, but we also disable the field
        # here to prevent that control being bypassed by a request sent
        # directly to the server.
        if self.instance.get_ticket() is None:
            self.fields['is_ukpa_member'].disabled = True

    def _post_clean(self):
        super()._post_clean()

        if self.cleaned_data.get('dont_ask_demographics'):
            # We don't care abour errors from the demographic fields if user
            # has selected dont_ask_demographics.
            for key in [
                'year_of_birth',
                'gender',
                'ethnicity',
                'ethnicity_free_text',
                'nationality',
                'country_of_residence',
            ]:
                with suppress(KeyError):
                    del self._errors[key]
        else:
            # If user has chosen a gender/nationality/country_of_residence
            # that's not in the initial list of choices, Django will raise a
            # ValidationError, and won't set the corresponding model attribute,
            # so we remove the error and set the attribute manually.
            for key in ['gender', 'nationality', 'country_of_residence']:
                with suppress(KeyError):
                    del self._errors[key]

                if key in self.data:
                    self.cleaned_data[key] = self.data[key]
                    setattr(self.instance, key, self.data[key])

    def clean(self):
        super().clean()

        if self.cleaned_data.get('dont_ask_demographics'):
            # If user has selected dont_ask_demographics, clear out all
            # demographic fields so they get cleared on the model instance.
            for key in [
                'year_of_birth',
                'gender',
                'ethnicity',
                'ethnicity_free_text',
                'nationality',
                'country_of_residence',
            ]:
                self.cleaned_data[key] = None

        return self.cleaned_data

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import redirect, render

from .forms import ProfileForm, RegisterForm


@login_required
def profile(request):
    user = request.user

    context = {
        'name': user.name,
        'ticket': user.get_ticket(),
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'form': form,
        'js_paths': ['accounts/profile_form.js'],
    }

    return render(request, 'accounts/edit_profile.html', context)


def register(request):
    if request.user.is_authenticated:
        messages.error(request, 'You are already signed in!')
        return redirect('index')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.email_addr,
                password=form.cleaned_data['password1']
            )
            login(request, user)

            return redirect(request.POST.get('next', 'index'))

    else:
        form = RegisterForm()

    context = {
        'form': form,
        'next': request.GET.get('next', 'index'),
    }

    return render(request, 'registration/register.html', context)

accounts/templates/accounts/_profile_details.html
<div>
  <h3>Basic information</h3>
  <table class="table">
    <tr>
      <th class="col-md-4">Name</th>
      <td>{{ user.name }}</td>
    </tr>
    <tr>
      <th class="col-md-4">Email</th>
      <td>{{ user.email_addr }}</td>
    </tr>
  </table>
</div>

<div>
  <h3>Requirements</h3>
  <table class="table">
    <tr>
      <th class="col-md-4">Accessibility</th>
      <td>
        {% if user.accessibility_reqs_yn == None %}
        unknown
        {% elif user.accessibility_reqs_yn %}
        {{ user.accessibility_reqs }}
        {% else %}
        none
        {% endif %}
      </td>
    </tr>
    <tr>
      <th class="col-md-4">Childcare</th>
      <td>
        {% if user.childcare_reqs_yn == None %}
        unknown
        {% elif user.childcare_reqs_yn %}
        {{ user.childcare_reqs }}
        {% else %}
        none
        {% endif %}
      </td>
    </tr>
    <tr>
      <th class="col-md-4">Dietary</th>
      <td>
        {% if user.dietary_reqs_yn == None %}
        unknown
        {% elif user.dietary_reqs_yn %}
        {{ user.dietary_reqs }}
        {% else %}
        none
        {% endif %}
      </td>
    </tr>
  </table>
</div>

{% if user.things_volunteered_for %}
<div>
  <h3>Volunteering at the conference</h3>

  <p>You have volunteered to:</p>
  <ul>
    {% for thing in user.things_volunteered_for %}
    <li>{{ thing }}</li>
    {% endfor %}
  </ul>
  <p>Thank you for volunteering!  We will be in touch to discuss how you can help.</p>
</div>
{% endif %}

<div>
  <h3>Evening events</h3>
  <table class="table">
    <tr>
      <th class="col-md-4">Thursday evening code dojo</th>
      <td>
        {% if user.coming_to_dojo == None %}
        unknown
        {% elif user.coming_to_dojo %}
        Yes
        {% else %}
        No
        {% endif %}
      </td>
    </tr>

    <tr>
      <th class="col-md-4">Saturday evening board games</th>
      <td>
        {% if user.coming_to_board_games == None %}
        unknown
        {% elif user.coming_to_board_games %}
        Yes
        {% else %}
        No
        {% endif %}
      </td>
    </tr>
  </table>
</div>

{% if user.get_ticket is not None %}
<div>
  <h3>UK Python Association</h3>
    <table class="table">
      <tr>
        <th class="col-md-4">Membership</th>
        <td>
          {% if user.is_ukpa_member == None %}
          unknown
          {% elif user.is_ukpa_member %}
          Yes
          {% else %}
          No
          {% endif %}
        </td>
      </tr>
    </table>
</div>
{% endif %}

<div>
  <h3>Demographics</h3>
  {% if user.dont_ask_demographics %}
  <p>You have opted not to share demographic information with us.</p>
  {% else %}
  <table class="table">
    <tr>
      <th class="col-md-4">Year of birth</th>
      <td>{{ user.year_of_birth|default:"unknown" }}</td>
    </tr>
    <tr>
      <th class="col-md-4">Gender</th>
      <td>{{ user.gender|default:"unknown" }}</td>
    </tr>
    <tr>
      <th class="col-md-4">Ethnicity</th>
      <td>
        {% if 'please describe' in user.ethnicity %}
        {{ user.ethnicity_free_text }}
        {% else %}
        {{ user.ethnicity|default:"unknown" }}
        {% endif %}
      </td>
    </tr>
    <tr>
      <th class="col-md-4">Nationality</th>
      <td>{{ user.nationality|default:"unknown" }}</td>
    </tr>
    <tr>
      <th class="col-md-4">Country of residence</th>
      <td>{{ user.country_of_residence|default:"unknown" }}</td>
    </tr>
  </table>
  {% endif %}
</div>

accounts/templates/accounts/edit_profile.html
{% extends 'ironcage/base.html' %}

{% load bootstrap3 %}

{% block content %}
<div class="row">
  <div class="col-md-8">
    <form method="post">
      {% csrf_token %}
      <div>
        <h3>Basic information</h3>
        <table class="table">
          <tr>
            <th class="col-md-4">Name (this will appear on your conference badge)</th>
            <td>{% bootstrap_field form.name layout='inline' %}</td>
          </tr>
          <tr>
            <th class="col-md-4">Email address</th>
            <td>{% bootstrap_field form.email_addr layout='inline' %}</td>
          </tr>
        </table>
      </div>

      <div>
        <h3>Requirements</h3>
        <table class="table">
          <tr>
            <th class="col-md-4">Do you have any accessibility requirements?</th>
            <td>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default{% if form.accessibility_reqs_yn.value == True %} active{% endif %}">
                  <input type="radio" name="accessibility_reqs_yn" value="2" {% if form.accessibility_reqs_yn.value == True %} checked{% endif %}>Yes
                </label>
                <label class="btn btn-default{% if form.accessibility_reqs_yn.value == False %} active{% endif %}">
                  <input type="radio" name="accessibility_reqs_yn" value="3" {% if form.accessibility_reqs_yn.value == False %} checked{% endif %}>No
                </label>
              </div>
              {% bootstrap_field form.accessibility_reqs layout='inline' placeholder='Please tell us more' %}
            </td>
          </tr>

          <tr>
            <th class="col-md-4">Do you have any childcare requirements?</th>
            <td>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default{% if form.childcare_reqs_yn.value == True %} active{% endif %}">
                  <input type="radio" name="childcare_reqs_yn" value="2" {% if form.childcare_reqs_yn.value == True %} checked{% endif %}>Yes
                </label>
                <label class="btn btn-default{% if form.childcare_reqs_yn.value == False %} active{% endif %}">
                  <input type="radio" name="childcare_reqs_yn" value="3" {% if form.childcare_reqs_yn.value == False %} checked{% endif %}>No
                </label>
              </div>
              {% bootstrap_field form.childcare_reqs layout='inline' placeholder='Please tell us more' %}
            </td>
          </tr>

          <tr>
            <th class="col-md-4">Do you have any dietary requirements?</th>
            <td>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default{% if form.dietary_reqs_yn.value == True %} active{% endif %}">
                  <input type="radio" name="dietary_reqs_yn" value="2" {% if form.dietary_reqs_yn.value == True %} checked{% endif %}>Yes
                </label>
                <label class="btn btn-default{% if form.dietary_reqs_yn.value == False %} active{% endif %}">
                  <input type="radio" name="dietary_reqs_yn" value="3" {% if form.dietary_reqs_yn.value == False %} checked{% endif %}>No
                </label>
              </div>
              {% bootstrap_field form.dietary_reqs layout='inline' placeholder='Please tell us more' %}
            </td>
          </tr>
        </table>
      </div>

      <div>
        <h3>Volunteering</h3>
        <p>Are you able to help us with the following?</p>
        <table class="table">
          <tr>
            <th class="col-md-4">Videoing talks</th>
            <td>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default{% if form.volunteer_videoer.value == True %} active{% endif %}">
                  <input type="radio" name="volunteer_videoer" value="2" {% if form.volunteer_videoer.value == True %} checked{% endif %}>Yes
                </label>
                <label class="btn btn-default{% if form.volunteer_videoer.value == False %} active{% endif %}">
                  <input type="radio" name="volunteer_videoer" value="3" {% if form.volunteer_videoer.value == False %} checked{% endif %}>No
                </label>
              </div>
            </td>
          </tr>

          <tr>
            <th class="col-md-4">Staffing the registration desk</th>
            <td>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default{% if form.volunteer_reg_desk.value == True %} active{% endif %}">
                  <input type="radio" name="volunteer_reg_desk" value="2" {% if form.volunteer_videoer.value == True %} checked{% endif %}>Yes
                </label>
                <label class="btn btn-default{% if form.volunteer_reg_desk.value == False %} active{% endif %}">
                  <input type="radio" name="volunteer_reg_desk" value="3" {% if form.volunteer_videoer.value == False %} checked{% endif %}>No
                </label>
              </div>
            </td>
          </tr>
        </table>
      </div>

      <div>
        <h3>Evening events</h3>
        <p>Please tell us if you plan to come to the following</p>
        <table class="table">
          <tr>
            <th class="col-md-4">Thursday evening code dojo</th>
            <td>Tickets for the dojo are no longer available.</td>
          </tr>

          <tr>
            <th class="col-md-4">Saturday evening board games</th>
            <td>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default{% if form.coming_to_board_games.value == True %} active{% endif %}">
                  <input type="radio" name="coming_to_board_games" value="2" {% if form.coming_to_board_games.value == True %} checked{% endif %}>Yes
                </label>
                <label class="btn btn-default{% if form.coming_to_board_games.value == False %} active{% endif %}">
                  <input type="radio" name="coming_to_board_games" value="3" {% if form.coming_to_board_games.value == False %} checked{% endif %}>No
                </label>
              </div>
            </td>
          </tr>
        </table>
      </div>

      {% if user.get_ticket is not None %}
      <div>
        <h3>UK Python Association (UKPA)</h3>
        <p>You can read more details about the UKPA and becoming a member on the <a href="http://2017.pyconuk.org/ukpa/">conference website</a></p>
        <table class="table">
          <tr>
            <th class="col-md-4">Do you wish to become a member of the UKPA?</th>
            <td>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default{% if form.is_ukpa_member.value == True %} active{% endif %}">
                  <input type="radio" name="is_ukpa_member" value="2" {% if form.is_ukpa_member.value == True %} checked{% endif %}>Yes
                </label>
                <label class="btn btn-default{% if form.is_ukpa_member.value == False %} active{% endif %}">
                  <input type="radio" name="is_ukpa_member" value="3" {% if form.is_ukpa_member.value == False %} checked{% endif %}>No
                </label>
              </div>
            </td>
          </tr>
        </table>
      </div>
      {% endif %}

      <div>
        <h3>Demographics</h3>

        <p>All fields are optional, and if you'd prefer not to share this information with us, just click "Don't ask me about this" below.</p>

        <!-- TODO: reinstate -->
        <!-- <p><a href="">Why do we collect this information?</a></p> -->

        <table class="table">
          <tr>
            <th class="col-md-4">Don't ask me about this</th>
            <td><input type="checkbox" name="dont_ask_demographics" id="id_dont_ask_demographics"{% if form.dont_ask_demographics.value == True %} checked{% endif %} /></td>
          </tr>
          <tr class="demographics-field">
            <th class="col-md-4">Year of birth</th>
            <td>{% bootstrap_field form.year_of_birth layout='inline' %}</td>
          </tr>
          <tr class="demographics-field">
            <th class="col-md-4">Gender</th>
            <td>
              {% bootstrap_field form.gender layout='inline' %}
              <input type="text" maxlength="100" class="form-control" placeholder="Please specify" id="id_gender_free_text" />
            </td>
          </tr>
          <tr class="demographics-field">
            <th class="col-md-4">Ethnicity</th>
            <td>
              {% bootstrap_field form.ethnicity layout='inline' %}
              {% bootstrap_field form.ethnicity_free_text layout='inline' %}
            </td>
          </tr>
          <tr class="demographics-field">
            <th class="col-md-4">Nationality</th>
            <td>
              {% bootstrap_field form.nationality layout='inline' %}
              <input type="text" maxlength="100" class="form-control" placeholder="Please specify" id="id_nationality_free_text" />
            </td>
          </tr>
          <tr class="demographics-field">
            <th class="col-md-4">Country of residence</th>
            <td>
              {% bootstrap_field form.country_of_residence layout='inline' %}
              <input type="text" maxlength="100" class="form-control" placeholder="Please specify" id="id_country_of_residence_free_text" />
            </td>
          </tr>
        </table>
      </div>

      <button type="submit" class="btn btn-primary">Update my profile</button>
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'ironcage/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-8">
    {% include './_profile_details.html' %}

    <a href="{% url 'accounts:edit_profile' %}" type="button" class="btn btn-primary">Update my profile</a>
  </div>
</div>
{% endblock %}