cfp/urls.py
from django.conf.urls import url

from . import views

app_name = 'cfp'

urlpatterns = [
    url(r'^proposals/new/$', views.new_proposal, name='new_proposal'),
    url(r'^proposals/(?P<proposal_id>\w+)/$', views.proposal, name='proposal'),
    url(r'^proposals/(?P<proposal_id>\w+)/edit/$', views.proposal_edit, name='proposal_edit'),
    url(r'^proposals/(?P<proposal_id>\w+)/delete/$', views.proposal_delete, name='proposal_delete'),
    url(r'^voting/$', views.voting_index, name='voting_index'),
    url(r'^voting/reviewed/$', views.voting_reviewed_proposals, name='voting_reviewed_proposals'),
    url(r'^voting/unreviewed/$', views.voting_unreviewed_proposals, name='voting_unreviewed_proposals'),
    url(r'^voting/of-interest/$', views.voting_proposals_of_interest, name='voting_proposals_of_interest'),
    url(r'^voting/not-of-interest/$', views.voting_proposals_not_of_interest, name='voting_proposals_not_of_interest'),
    url(r'^voting/proposals/(?P<proposal_id>\w+)/$', views.voting_proposal, name='voting_proposal'),
]

ironcage/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

import accounts.views
import ironcage.views


if settings.MAINTENANCE_MODE:
    urlpatterns = [
        url('.*', ironcage.views.maintenance_mode)
    ]
else:
    urlpatterns = [
        url(r'^accounts/register/', accounts.views.register, name='register'),
        url(r'^accounts/', include('django.contrib.auth.urls')),
        url(r'^accommodation/', include('accommodation.urls')),
        url(r'^admin/', admin.site.urls),
        url(r'^children/', include('children.urls')),
        url(r'^cfp/', include('cfp.urls')),
        url(r'^dinners/', include('dinners.urls')),
        url(r'^grants/', include('grants.urls')),
        url(r'^profile/', include('accounts.urls')),
        url(r'^reports/', include('reports.urls')),
        url(r'^tickets/', include('tickets.urls')),
        url(r'^ukpa/', include('ukpa.urls')),
        url(r'^$', ironcage.views.index, name='index'),
        url(r'^500/$', ironcage.views.error, name='error'),
        url(r'^log/$', ironcage.views.log, name='log'),
        url(r'^avatar/', include('avatar.urls')),
        url(r'^payments/', include('payments.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

payments/urls.py
from django.conf.urls import url

from . import views

app_name = 'payments'

urlpatterns = [
    url(r'^orders/(?P<invoice_id>\w+)/$', views.order, name='order'),
    url(r'^payment/(?P<payment_id>\w+)/$', views.payment, name='payment'),
    url(r'^orders/(?P<invoice_id>\w+)/payment/$', views.invoice_payment, name='invoice_payment'),
]

tickets/urls.py
from django.conf.urls import url

from . import views

app_name = 'tickets'

urlpatterns = [
    url(r'^orders/new/$', views.new_order, name='new_order'),
    url(r'^orders/confirm/$', views.order_confirm, name='order_confirm'),
    url(r'^orders/edit/$', views.order_edit, name='order_edit'),
    url(r'^tickets/(?P<ticket_id>\w+)/$', views.ticket, name='ticket'),
    url(r'^tickets/(?P<ticket_id>\w+)/edit/$', views.ticket_edit, name='ticket_edit'),
    url(r'^invitations/(?P<token>\w+)/$', views.ticket_invitation, name='ticket_invitation'),
]

payments/models.py
from decimal import Decimal

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models, transaction
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.urls import reverse
from django.core.exceptions import ValidationError


from payments.exceptions import (
    InvoiceHasPaymentsException,
    ItemNotOnInvoiceException,
)
import structlog

logger = structlog.get_logger()


STANDARD_RATE_VAT = Decimal(20.0)
ZERO_RATE_VAT = Decimal(0.0)


class SalesRecord(models.Model):

    CREDIT_RECORD = False

    SEQUENCE_PREFIX = ''

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    company_name = models.CharField(max_length=200, null=True, blank=True)
    company_addr = models.TextField(null=True, blank=True)

    purchaser = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  related_name='%(class)ss',
                                  on_delete=models.PROTECT)

    total_ex_vat = models.DecimalField(max_digits=7, decimal_places=2,
                                       default=Decimal(0.0))

    total_vat = models.DecimalField(max_digits=7, decimal_places=2,
                                    default=Decimal(0.0))

    class Meta:
        abstract = True

    def clean(self):
        if (self.company_name is not None and self.company_addr is None) \
                or (self.company_name is None and self.company_addr is not None):
            raise ValidationError('Both company name and company address must be provided.')

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    @property
    def item_id(self):
        return '{}-{}'.format(self.SEQUENCE_PREFIX, self.id)

    def _recalculate_total(self):
        self.total_ex_vat = Decimal(0)
        self.total_vat = Decimal(0)

        for row in self.rows.all():
            if self.CREDIT_RECORD:
                self.total_ex_vat -= row.total_ex_vat
                self.total_vat -= row.total_vat
            else:
                self.total_ex_vat += row.total_ex_vat
                self.total_vat += row.total_vat

        self.total_ex_vat = round(self.total_ex_vat, 2)
        self.total_vat = round(self.total_vat, 2)

        self.save()

    @property
    def total_inc_vat(self):
        return self.total_ex_vat + self.total_vat

    def get_absolute_url(self):
        return reverse('payments:order', args=[self.id])

    @property
    def total_pence_inc_vat(self):
        return int(100 * self.total_inc_vat)

    def add_item(self, item, vat_rate=STANDARD_RATE_VAT):
        logger.info('add invoice row', invoice=self.id, item=item.id,
                    item_type=type(item), vat_rate=vat_rate)

        # Does the invoice have any payments against it?
        if self.payments.count() != 0:
            logger.error('invoice has payments', invoice=self.id)
            raise InvoiceHasPaymentsException

        # TODO: Additional logic regarding:
        # - Only add to credit note if already on paid invoice
        # - Only add to invoice if not already on paid invoice with no
        #   credit notes
        # i.e. ensure each item can be paid for zero or one times

        if type(self) == Invoice:
            row_model = InvoiceRow
        elif type(self) == CreditNote:
            row_model = CreditNoteRow

        with transaction.atomic():
            return row_model.objects.create(
                parent=self,
                item=item,
                total_ex_vat=item.cost_excl_vat(),
                vat_rate=vat_rate
            )

    def delete_item(self, item):
        logger.info('delete invoice row', invoice=self.id, item=item.id,
                    item_type=type(item))

        # Is the item on the invoice?
        # TODO: Make this less crappy
        content_type = ContentType.objects.get_for_model(item)

        rows_with_item = self.rows.filter(
            content_type=content_type,
            object_id=item.id
        ).count()

        if rows_with_item == 0:
            logger.error('item not on invoice', invoice=self.id)
            raise ItemNotOnInvoiceException

        # Does the invoice have any payments against it?
        if self.payments.count() != 0:
            logger.error('invoice has payments', invoice=self.id)
            raise InvoiceHasPaymentsException

        if type(self) == Invoice:
            row_model = InvoiceRow
        elif type(self) == CreditNote:
            row_model = CreditNoteRow

        with transaction.atomic():
            deleted_row = row_model.objects.get(
                parent=self,
                content_type=content_type,
                object_id=item.id
            )

            deleted_row.delete()

    @property
    def payment_required(self):
        # TODO: but is it the right amount?
        return self.payments.filter(
            status=Payment.SUCCESSFUL
        ).count() < 1

    @property
    def successful_payment(self):
        try:
            return self.payments.get(
                status=Payment.SUCCESSFUL
            )
        except Payment.DoesNotExist:
            return None

    @property
    def payment_status(self):
        # Worst to best
        if self.payments.count():
            STATUS_ORDER = (
                Payment.CHARGEBACK,
                Payment.REFUNDED,
                Payment.ERRORED,
                Payment.FAILED,
                Payment.SUCCESSFUL
            )

            status_index = len(STATUS_ORDER) + 1

            for payment in self.payments.all():
                if STATUS_ORDER.index(payment.status) < status_index:
                    status_index = STATUS_ORDER.index(payment.status)

            return STATUS_ORDER[status_index]

        return None

    def tickets(self):
        from tickets.models import Ticket
        tickets = []

        for row in self.rows.all():
            if isinstance(row.item, Ticket):
                tickets.append(row.item)

        return tickets

    def unclaimed_tickets(self):
        from tickets.models import Ticket, TicketInvitation
        tickets = []

        for row in self.rows.all():
            if isinstance(row.item, Ticket) \
                    and hasattr(row.item, 'invitation') \
                    and row.item.invitation.status == TicketInvitation.UNCLAIMED:
                tickets.append(row.item)

        return tickets

    def brief_summary(self):
        return f'{self.rows.count()} items, £{self.total_inc_vat}'


class SalesRecordRow(models.Model):

    VAT_RATE_CHOICES = (
        (STANDARD_RATE_VAT, 'Standard 20%'),
        (ZERO_RATE_VAT, 'Zero Rated'),
    )

    content_type = models.ForeignKey(ContentType, on_delete=models.DO_NOTHING)
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    total_ex_vat = models.DecimalField(max_digits=7, decimal_places=2)

    vat_rate = models.DecimalField(max_digits=4, decimal_places=2,
                                   choices=VAT_RATE_CHOICES)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    @property
    def total_inc_vat(self):
        vat_rate_as_percent = 1 + (self.vat_rate / Decimal(100))
        return self.total_ex_vat * vat_rate_as_percent

    @property
    def total_vat(self):
        vat_rate_as_percent = self.vat_rate / Decimal(100)
        return self.total_ex_vat * vat_rate_as_percent


class Payment(models.Model):

    STRIPE = 'S'

    METHOD_CHOICES = (
        (STRIPE, 'Stripe'),
    )

    SUCCESSFUL = 'SUC'
    FAILED = 'FLD'
    ERRORED = 'ERR'
    REFUNDED = 'RFD'
    CHARGEBACK = 'CBK'

    STATUS_CHOICES = (
        (SUCCESSFUL, 'Successful'),
        (FAILED, 'Failed'),
        (ERRORED, 'Errored'),
        (REFUNDED, 'Refunded'),
        (CHARGEBACK, 'Chargeback'),
    )

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    limit = models.Q(app_label='payments', model='invoice') | \
        models.Q(app_label='payments', model='credit_note')
    content_type = models.ForeignKey(ContentType, on_delete=models.DO_NOTHING,
                                     limit_choices_to=limit)
    object_id = models.PositiveIntegerField()
    invoice = GenericForeignKey('content_type', 'object_id')

    method = models.CharField(max_length=1, choices=METHOD_CHOICES)
    status = models.CharField(max_length=3, choices=STATUS_CHOICES)
    charge_id = models.CharField(max_length=80)
    charge_failure_reason = models.CharField(max_length=400, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    amount = models.DecimalField(max_digits=7, decimal_places=2)


class Invoice(SalesRecord):

    CREDIT_RECORD = False

    SEQUENCE_PREFIX = 'IC-2018'

    payments = GenericRelation(Payment)


class CreditNote(SalesRecord):

    CREDIT_RECORD = True

    SEQUENCE_PREFIX = 'CI-2018'

    CREATED_BY_MISTAKE = 'Mistake'
    REFUNDED_ORDER = 'Refunded'
    ENTITLED_TO_FREE = 'Entitled to Free'
    PAYMENT_BOUNCED = 'Payment Bounced'
    CHARGEBACK = 'Chargeback'
    WRONG_TICKET_TYPE = 'Wrong ticket type'
    ATTENDANCE_REFUSED = 'Attendance Refused'
    COC_BREACH = 'Breach of CoC'
    VISA_ISSUES = 'Issues with travel Visa'
    TRAVEL_ISSUES = 'Issues with travel'
    ACCOMMODATION_ISSUES = 'Issues with accommodation'

    REASON_CHOICES = (
        (CREATED_BY_MISTAKE, 'Order created by mistake'),
        (REFUNDED_ORDER, 'Purchaser requested refund'),

payments/views.py
from datetime import datetime, timezone

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_POST

from payments import actions as payment_actions
from payments.models import Invoice, Payment
from tickets import actions
from tickets.forms import CompanyDetailsForm, TicketForm, TicketForSelfForm, TicketForOthersFormSet
from tickets.models import Ticket, TicketInvitation
from tickets.prices import PRICES_INCL_VAT, cost_incl_vat


@login_required
def order(request, invoice_id):
    invoice = get_object_or_404(Invoice, pk=invoice_id)

    if request.user != invoice.purchaser:
        messages.warning(request, 'Only the purchaser of an invoice can view the invoice')
        return redirect('index')

    # TODO
    # if not invoice.successful_payment:
    #     if request.user.get_ticket() is not None and invoice.unconfirmed_details['days_for_self']:
    #         messages.warning(request, 'You already have a ticket.  Please amend your invoice.')
    #         return redirect('tickets:order_edit', invoice.invoice_id)

    if invoice.payment_status == Payment.FAILED:
        messages.error(request, f'Payment for this invoice failed')
    elif invoice.payment_status == Payment.ERRORED:
        messages.error(request, 'There was an error creating your invoice. Your card may have been charged, but if so the charge will have been refunded.  Please make a new invoice.')

    ticket = request.user.get_ticket()
    if ticket is not None and ticket.invoice != invoice:
        ticket = None

    context = {
        'invoice': invoice,
        'ticket': ticket,
        'stripe_api_key': settings.STRIPE_API_KEY_PUBLISHABLE,
    }
    return render(request, 'payments/order.html', context)


@login_required
@require_POST
def invoice_payment(request, invoice_id):
    invoice = get_object_or_404(Invoice, pk=invoice_id)

    if request.user != invoice.purchaser:
        messages.warning(request, 'Only the purchaser of an invoice can pay for the invoice')
        return redirect('index')

    if invoice.successful_payment:
        messages.error(request, 'This invoice has already been paid')
        return redirect(invoice)

    # if request.user.get_ticket() is not None and invoice.unconfirmed_details['days_for_self']:
    #     messages.warning(request, 'You already have a ticket.  Please amend your invoice.  Your card has not been charged.')
    #     return redirect('tickets:order_edit', invoice.invoice_id)

    token = request.POST['stripeToken']
    payment = payment_actions.pay_invoice_by_stripe(invoice, token)

    if not invoice.payment_required and payment.status == Payment.SUCCESSFUL:
        messages.success(request, 'Payment for this invoice has been received.')
    else:
        messages.error(request, f'There was an error with your payment: {payment.charge_failure_reason}')

    return redirect(invoice)


@login_required
def payment(request, payment_id):
    payment = get_object_or_404(Payment, pk=payment_id)

    if request.user != payment.invoice.purchaser:
        messages.warning(request, 'Only the purchaser of an order can view the receipt')
        return redirect('index')

    context = {
        'payment': payment,
        'invoice': payment.invoice,
        'title': f'PyCon UK 2018 Receipt {payment.id}',
        'no_navbar': True,
    }
    return render(request, 'payments/payment_receipt.html', context)

payments/templates/payments/_invoice_details.html
<div class="row">
  <div class="col-md-4">
    <table class="table table-condensed">
      <tr>
        <th>Invoice Number</th>
        <td>{{ invoice.item_id }}</td>
      </tr>
      <tr>
        <th>Date</th>
        <td>{{ invoice.created_at|date }}</td>
      </tr>
      <tr>
        <th>Status</th>
        <td>{% if invoice.payment_required %}Unpaid{% else %}Paid{% endif %}</td>
      </tr>
      {% if invoice.rate == 'corporate' %}
      <tr>
        <th>Company</th>
        <td>{{ invoice.company_name }}</td>
      </tr>
      <tr>
        <th>Address</th>
        <td>{{ invoice.company_addr_formatted }}</td>
      </tr>
      {% endif %}
      <tr>
        <th>Total (excl. VAT)</th>
        <td>&pound;{{ invoice.total_ex_vat|floatformat:2 }}</td>
      </tr>
      <tr>
        <th>VAT</th>
        <td>&pound;{{ invoice.total_vat|floatformat:2 }}</td>
      </tr>
      <tr>
        <th>Total (incl. VAT)</th>
        <td>&pound;{{ invoice.total_inc_vat|floatformat:2 }}</td>
      </tr>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>Invoice details</h3>

    <table class="table table-condensed">
      <tr>
        <th>Item ID</th>
        <th>Item</th>
        <th>Quantity</th>
        <th>Total ex VAT</th>
        <th>VAT Rate</th>
        <th>Total inc VAT</th>
      </tr>
      {% for row in invoice.rows.all %}
      <tr>
        <td>{{ row.item.item_id }}</td>
        <td>{{ row.item.invoice_description }}</td>
        <td>1</td>
        <td>&pound;{{ row.total_ex_vat|floatformat:2 }}</td>
        <td>{{ row.vat_rate|floatformat:0 }}%</td>
        <td>&pound;{{ row.total_inc_vat|floatformat:2 }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

payments/templates/payments/order.html
{% extends 'ironcage/base.html' %}

{% load static %}

{% block content %}
<h1>Details of your order</h1>

{% include './_invoice_details.html' %}

{% if invoice.payment_status == 'FLD' or invoice.payment_status is None %}
<div id="stripe-form">
  <form action="{% url 'payments:invoice_payment' invoice_id=invoice.id %}" method="POST">
    {% csrf_token %}
    <script
      src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="{{ stripe_api_key }}"
      data-amount="{{ invoice.total_pence_inc_vat }}"
      data-currency="gbp"
      data-name="PyCon UK Society Ltd"
      data-image="{% static 'ironcage/img/yellow.png' %}"
      data-description="PyCon UK 2018 invoice {{ invoice.item_id }}"
      data-locale="auto"
      data-email="{{ invoice.purchaser.email_addr }}"
    >
    </script>

    <!-- https://stackoverflow.com/a/41527060 -->
    <style>.stripe-button-el { display: none; }</style>
    <button class="btn btn-primary" type="submit">Pay by card</button>
  </form>

</div>
{% elif not invoice.payment_required %}
<div class="row">
  <div class="col-md-6">
    {% if invoice.payments.count == 1 %}
      <a href="{% url 'payments:payment' invoice.payments.first.id %}" class="btn btn-primary">View receipt</a>
    {% else %}
      {% for payment in invoice.payments.all %}
        <a href="{% url 'payments:payment' payment.id %}" class="">Receipt #{{ payment.id }} ({{payment.get_status_display}})</a><br>
      {% endfor %}
    {% endif %}
    {% if ticket %}
    <a href="{% url 'tickets:ticket' ticket.ticket_id %}" class="btn btn-primary">View your ticket</a>
    {% endif %}
  </div>
</div>
{% endif %}

{% endblock %}

payments/templates/payments/payment_receipt.html
{% extends 'ironcage/base.html' %}

{% block content %}
<h1>Receipt for PyCon UK 2018</h1>

<p>Issued by the PyCon UK Society Ltd, c/o Acconomy, Arena Business Centre, Holyrood Close, Poole, BH17 7FJ, United Kingdom (VAT Number GB 249 2449 82)</p>

{% if payment.rate == 'corporate' %}
<p>Issued to {{ payment.company_name }}, {{ payment.company_addr_formatted }}</p>
{% else %}
<p>Issued to {{ invoice.purchaser.name }}, {{ invoice.purchaser.email_addr }}</p>
{% endif %}

<div class="row">
  <div class="col-md-4">
    <table class="table table-condensed">
      <tr>
        <th>Date</th>
        <td>{{ payment.created_at|date }}</td>
      </tr>

      <tr>
        <th>Invoice number</th>
        <td>{{ invoice.item_id }}</td>
      </tr>

      <tr>
        <th>Payment number</th>
        <td>{{ payment.id }}</td>
      </tr>

      <tr>
        <th>Total received</th>
        <td>&pound;{{ payment.amount }}</td>
      </tr>

      <tr>
        <th>Paid by</th>
        <td>{{ payment.get_method_display }}</td>
      </tr>

      <tr>
        <th>Payment status</th>
        <td>{{ payment.get_status_display }}{% if payment.status != payment.SUCCESSFUL %} ({{ payment.charge_failure_reason }}){% endif %}</td>
      </tr>

    </table>
  </div>
</div>

<h2>Invoice {{ invoice.item_id }} Detail</h2>

{% include './_invoice_details.html' %}
{% endblock %}