cfp/urls.py
from django.conf.urls import url

from . import views

app_name = 'cfp'

urlpatterns = [
    url(r'^proposals/new/$', views.new_proposal, name='new_proposal'),
    url(r'^proposals/(?P<proposal_id>\w+)/$', views.proposal, name='proposal'),
    url(r'^proposals/(?P<proposal_id>\w+)/edit/$', views.proposal_edit, name='proposal_edit'),
    url(r'^proposals/(?P<proposal_id>\w+)/delete/$', views.proposal_delete, name='proposal_delete'),
    url(r'^voting/$', views.voting_index, name='voting_index'),
    url(r'^voting/reviewed/$', views.voting_reviewed_proposals, name='voting_reviewed_proposals'),
    url(r'^voting/unreviewed/$', views.voting_unreviewed_proposals, name='voting_unreviewed_proposals'),
    url(r'^voting/of-interest/$', views.voting_proposals_of_interest, name='voting_proposals_of_interest'),
    url(r'^voting/not-of-interest/$', views.voting_proposals_not_of_interest, name='voting_proposals_not_of_interest'),
    url(r'^voting/proposals/(?P<proposal_id>\w+)/$', views.voting_proposal, name='voting_proposal'),
]

dinners/urls.py
from django.conf.urls import url

from . import views

app_name = 'dinners'

urlpatterns = [
    url(r'^contributors-dinner/$', views.contributors_dinner, name='contributors_dinner'),
    url(r'^conference-dinner/$', views.conference_dinner, name='conference_dinner'),
    url(r'^conference-dinner/payment/$', views.conference_dinner_payment, name='conference_dinner_payment'),
    url(r'^conference-dinner/receipt/$', views.conference_dinner_receipt, name='conference_dinner_receipt'),
]

grants/urls.py
from django.conf.urls import url

from . import views

app_name = 'grants'

urlpatterns = [
    url(r'^applications/new/$', views.new_application, name='new_application'),
    url(r'^applications/(?P<application_id>\w+)/$', views.application, name='application'),
    url(r'^applications/(?P<application_id>\w+)/edit/$', views.application_edit, name='application_edit'),
    url(r'^applications/(?P<application_id>\w+)/delete/$', views.application_delete, name='application_delete'),
]

ironcage/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

import accounts.views
import ironcage.views


if settings.MAINTENANCE_MODE:
    urlpatterns = [
        url('.*', ironcage.views.maintenance_mode)
    ]
else:
    urlpatterns = [
        url(r'^accounts/register/', accounts.views.register, name='register'),
        url(r'^accounts/', include('django.contrib.auth.urls')),
        url(r'^accommodation/', include('accommodation.urls')),
        url(r'^admin/', admin.site.urls),
        url(r'^children/', include('children.urls')),
        url(r'^cfp/', include('cfp.urls')),
        url(r'^dinners/', include('dinners.urls')),
        url(r'^grants/', include('grants.urls')),
        url(r'^profile/', include('accounts.urls')),
        url(r'^reports/', include('reports.urls')),
        url(r'^tickets/', include('tickets.urls')),
        url(r'^ukpa/', include('ukpa.urls')),
        url(r'^$', ironcage.views.index, name='index'),
        url(r'^500/$', ironcage.views.error, name='error'),
        url(r'^log/$', ironcage.views.log, name='log'),
        url(r'^avatar/', include('avatar.urls')),
        url(r'^payments/', include('payments.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

reports/urls.py
from django.conf.urls import url

from . import reports, views

app_name = 'reports'

urlpatterns = [
    url(report.path(), report.as_view(), name=report.url_name())
    for report in reports.reports
]

urlpatterns.extend([
    url(r'^accounts/users/(?P<user_id>\w+)/$', views.accounts_user, name='accounts_user'),
    url(r'^cfp/proposals/(?P<proposal_id>\w+)/$', views.cfp_proposal, name='cfp_proposal'),
    url(r'^grants/applications/(?P<application_id>\w+)/$', views.grants_application, name='grants_application'),
    url(r'^tickets/orders/(?P<order_id>\w+)/$', views.tickets_order, name='tickets_order'),
    url(r'^tickets/tickets/(?P<ticket_id>\w+)/$', views.tickets_ticket, name='tickets_ticket'),
    url('^$', views.index, name='index'),
])

ukpa/urls.py
from django.conf.urls import url

from . import views

app_name = 'ukpa'

urlpatterns = [
    url(r'^nominations/new/$', views.new_nomination, name='new_nomination'),
    url(r'^nominations/(?P<nomination_id>\w+)/$', views.nomination, name='nomination'),
    url(r'^nominations/(?P<nomination_id>\w+)/edit/$', views.nomination_edit, name='nomination_edit'),
    url(r'^nominations/(?P<nomination_id>\w+)/delete/$', views.nomination_delete, name='nomination_delete'),
]

ironcage/views.py
from datetime import datetime, timezone

import structlog

from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect, render


logger = structlog.get_logger()


def index(request):
    user = request.user

    if user.is_authenticated:
        if user.get_ticket() is not None and not user.profile_complete():
            messages.warning(request, 'Your profile is incomplete')
        context = {
            'ticket': user.get_ticket(),
            'orders': user.invoices.all(),
            'grant_application': user.get_grant_application(),
            'proposals': user.proposals.all(),
            'nomination': user.get_nomination(),
            'is_contributor': user.is_contributor,
            'free_dinner_booking': user.get_free_dinner_booking(),
            'conference_dinner_booking': user.get_conference_dinner_booking(),
            'contributors_dinner_booking': user.get_contributors_dinner_booking(),
            'cfp_open': datetime.now(timezone.utc) < settings.CFP_CLOSE_AT,
            'grant_applications_open': datetime.now(timezone.utc) < settings.GRANT_APPLICATIONS_CLOSE_AT,
            'ticket_sales_open': datetime.now(timezone.utc) < settings.TICKET_SALES_CLOSE_AT,
        }
    else:
        context = {
            'cfp_open': datetime.now(timezone.utc) < settings.CFP_CLOSE_AT,
            'grant_applications_open': datetime.now(timezone.utc) < settings.GRANT_APPLICATIONS_CLOSE_AT,
            'ticket_sales_open': datetime.now(timezone.utc) < settings.TICKET_SALES_CLOSE_AT,
        }

    return render(request, 'ironcage/index.html', context)


def error(request):
    1 / 0


def log(request):
    logger.info('Test log')
    return redirect('index')


def maintenance_mode(request):
    return render(request, 'ironcage/maintenance_mode.html')

ironcage/templates/ironcage/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-plugins/bootstrap-datepicker/css/bootstrap-datepicker3.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'tickets/tickets.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'dinners/dinners.css' %}" />
    <title>{{ title|default:"PyCon UK 2018 HQ" }}</title>
  </head>
  <body>
    <div class="container">
      {% if not no_navbar %}
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">PyCon UK HQ</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_staff %}
              <li><a href="{% url 'reports:index' %}">Reports</a></li>
              {% endif %}
              {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}">Sign out</a></li>
              {% else %}
              <li><a href="{% url 'login' %}?next={{ request.path }}">Sign in</a></li>
              <li><a href="{% url 'register' %}?next={{ request.path }}">Sign up</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      {% endif %}
      <div class="row">
        <div class="col-md-12">
          {% for message in messages %}
          {% if message.tags == 'error' %}
          <div class="alert alert-danger" role="alert">{{ message }}</div>
          {% else %}
          <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
          {% endif %}
          {% endfor %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          {% block content %}
          {% endblock %}
        </div>
      </div>
      <hr />
    </div>
  </body>
  <script src="{% static 'jquery-3.1.0/js/jquery.js' %}"></script>
  <script src="{% static 'jquery-plugins/js/jquery.formset.js' %}"></script>
  <script src="{% static 'bootstrap-3.3.7/js/bootstrap.js' %}"></script>
  <script src="{% static 'bootstrap-plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>

  <script>
    {% block json_data %}
    {% endblock %}
  </script>

  {% for path in js_paths %}
  <script src="{% static path %}"></script>
  {% endfor %}
</html>

ironcage/templates/ironcage/index.html
{% extends 'ironcage/base.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<p>Hello, {{ request.user.name }}</p>
{% endif %}

<p>Welcome to the PyCon UK 2018 conference HQ.</p>

<p>The conference takes place at <a href="http://2018.pyconuk.org/venue/">Cardiff City Hall</a> from Saturday 15th to Wednesday 19th September 2018.  You can find out more about the conference <a href="http://2018.pyconuk.org/">on our website</a>.</p>

{% if ticket %}
<p>You have a ticket for {{ ticket.details.days }}.</p>
{% endif %}

<p>Here, you can:</p>
<ul>
{% if ticket %}
    <li><a href="{% url 'tickets:ticket' ticket.ticket_id %}">View your conference ticket</a></li>
    <li><a href="{% url 'accounts:profile' %}">Update your profile</a></li>
{% endif %}

{% if orders|length == 0 %}
    {% if ticket_sales_open %}
        <li><a href="{% url 'tickets:new_order' %}">Order conference tickets</a></li>
    {% endif %}
{% elif orders|length == 1 %}
    <li><a href="{% url 'payments:order' orders.0.id %}">View {% if not orders.0.successful_payment %}and pay for{% endif %} your order</a></li>
    {% if ticket_sales_open %}
        <li><a href="{% url 'tickets:new_order' %}">Order more conference tickets</a></li>
    {% endif %}
{% else %}
    <li>View your orders:</li>
    <ul>
      {% for order in orders %}
        <li><a href="{% url 'payments:order' order.id %}">Invoice {{ order.item_id }}</a> ({{ order.brief_summary }})</li>
      {% endfor %}
    </ul>
    {% if ticket_sales_open %}
        <li><a href="{% url 'tickets:new_order' %}">Order more conference tickets</a></li>
    {% endif %}
{% endif %}

{% if proposals|length == 0 %}
    {% if cfp_open %}
        <li><a href="{% url 'cfp:new_proposal' %}">Make a proposal to our Call for Participation</a></li>
    {% endif %}
{% elif proposals|length == 1 %}
    <li><a href="{% url 'cfp:proposal' proposals.0.proposal_id %}">View your proposal to our Call for Participation</a> ({{ proposals.0.title }})</li>
    {% if cfp_open %}
        <li><a href="{% url 'cfp:new_proposal' %}">Make another proposal to our Call for Participation</a></li>
    {% endif %}
{% else %}
    <li>View your proposals to our Call for Participation</li>
    <ul>
      {% for proposal in proposals %}
      <li><a href="{% url 'cfp:proposal' proposal.proposal_id %}">{{ proposal.title }}</a></li>
      {% endfor %}
    </ul>
    <li><a href="{% url 'cfp:new_proposal' %}">Make another proposal to our Call for Participation</a></li>
{% endif %}

{% if grant_application %}
    <li><a href="{% url 'grants:application' grant_application.application_id %}">View your application for financial assistance</a></li>
{% else %}
    {% if grant_applications_open %}
        <li><a href="{% url 'grants:new_application' %}">Apply for financial assistance</a></li>
    {% endif %}
{% endif %}

{% if nomination %}
    <li><a href="{% url 'ukpa:nomination' nomination.nomination_id %}">
    View your nomination for election as a UKPA Trustee</a></li>
{% endif %}

{% if is_contributor %}
    {% if free_dinner_booking %}
        {% if free_dinner_booking.venue == 'conference' %}
            <li><a href="{% url 'dinners:conference_dinner' %}">
            View your conference dinner booking
            </a></li>
        {% else %}
            <li><a href="{% url 'dinners:contributors_dinner' %}">
            View your contributors' dinner booking
            </a></li>
            <li><a href="{% url 'dinners:conference_dinner' %}">
            {% if conference_dinner_booking %}
                View your conference dinner booking
            {% else %}
                Make a booking for the conference dinner
            {% endif %}
            </a></li>
        {% endif %}
    {% else %}
        <li><a href="{% url 'dinners:contributors_dinner' %}">
        Make a booking for the contributors' dinner
        </a></li>
    {% endif %}
{% else %}
    <li><a href="{% url 'dinners:conference_dinner' %}">
    {% if conference_dinner_booking %}
        View your conference dinner booking
    {% else %}
        Make a booking for the conference dinner
    {% endif %}
    </a></li>
{% endif %}

</ul>

{% if ticket %}
    <p>We look forward to seeing you in Cardiff!</p>
{% else %}
    <p>We hope to see you in Cardiff!</p>
{% endif %}

<p>~ The PyCon UK Committee</p>
{% endblock %}

ironcage/templates/ironcage/maintenance_mode.html
<p>The site is undergoing maintenance.  Please check back later!</p>